# Generated by Django 2.0.3 on 2020-04-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='userid',
            new_name='user',
        ),
    ]
